services:
  scheduler-postgres:
    image: 'postgres:alpine'
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 7000:5432
    volumes:
      - './1-docker-data/scheduler-postgres/volumes/docker-entrypoint-initdb.d/01-init-scheduler-db.sh:/docker-entrypoint-initdb.d/01-init-scheduler-db.sh'
      - './1-docker-data/scheduler-postgres/volumes/pg-data:/var/lib/postgresql/data'
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    volumes:
      - ./1-docker-data/zookeeper/volumes/data:/var/lib/zookeeper/data
      - ./1-docker-data/zookeeper/volumes/log:/var/lib/zookeeper/log
    ports:
      - 7002:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    volumes:
      - ./1-docker-data/kafka/volumes/data:/var/lib/kafka/data
      - ./1-docker-data/kafka/volumes/logs:/tmp/kafka-logs
    ports:
      - 7003:7003
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER://kafka:9092,LISTENER_HOST://localhost:7003
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER:PLAINTEXT,LISTENER_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
    depends_on:
      - zookeeper
  scheduler:
    image: 'stepniewski.tech/dev-tools-scheduler:latest'
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - "${SCHEDULER_PATH}:/app"
      - "${PWD}/1-docker-data/scheduler/volumes/sbt:/.sbt"
      - "${PWD}/1-docker-data/scheduler/volumes/ivy:/.ivy"
      - "${PWD}/1-docker-data/scheduler/volumes/cache:/.cache"
      - "${PWD}/0-first-run/conf/scheduler.conf:/app/conf/scheduler.conf"
    ports:
      - 7001:7001
    depends_on:
      - scheduler-postgres
      - kafka

